functional:
  - Возможность просмотра повтора игры
  - Использование всех языков программирования
  - Мультиязычность (английский, русский)
  - Пользователь может выбрать уровень сложности
  - Пользователь может выбрать язык программирования в игре
  - Пользователь может создать игру с ботом
  - Пользователь может создать игру с другим игроком
  - Пользователь может просматривать список активных игр
  - Пользователь может сдаться в процессе игры
  - Пользователь может просматривать таблицу рейтинга за неделю/месяц/весь период

non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  
implicit:
  - Игрок не может изменять код соперника
  - Пользователь не может изменить рейтинг
  - Игроки не могут изменять условия задачи
  - Пользователь не может писать код в ходе просмотра игры 
